Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using ReelJunkies.Models.ViewModels;
using ReelJunkies.Services.Interfaces;
using System.Threading.Tasks;

namespace ReelJunkies.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IRemoteMovieService _tmdbMovieService;
        private readonly IDataMappingService _mappingService;

        public ActorsController(IRemoteMovieService tmdbMovieService,
                                IDataMappingService mappingService)
        {
            _tmdbMovieService = tmdbMovieService;
            _mappingService = mappingService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var actor = await _tmdbMovieService.ActorDetailAsync(id);
            actor = _mappingService.MapActorDetail(actor);

            var combinedCredits = await _tmdbMovieService.ActorCombinedCreditsAsync(id);

            var actorCombinedCredits = new VM_ActorMovies()
            {
                ActorDetail = actor,
                CombinedCredits = combinedCredits,
            };

            return View(actorCombinedCredits);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ReelJunkies.Data;
using ReelJunkies.Enums;
using ReelJunkies.Models;
using ReelJunkies.Models.TmDb;
using ReelJunkies.Models.ViewModels;
using ReelJunkies.Services.Interfaces;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ReelJunkies.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ApplicationDbContext _context;
        private readonly IRemoteMovieService _tmdbMovieService;
        private readonly IDataMappingService _dataMappingService;

        public HomeController(ApplicationDbContext context,
                              IRemoteMovieService tmdbMovieService,
                              ILogger<HomeController> logger,
                              IDataMappingService dataMappingService)
        {
            _context = context;
            _tmdbMovieService = tmdbMovieService;
            _logger = logger;
            _dataMappingService = dataMappingService;
        }


        public async Task<IActionResult> Index()
        {
            const int count = 12;
            const int page = 1;
            var Upcomming = await _tmdbMovieService.MovieSearchAsync(MovieCategory.upcoming, count, page);
            Upcomming.results = Upcomming.results.OrderByDescending(x => x.release_date).ToArray();

            var NowPlaying = await _tmdbMovieService.MovieSearchAsync(MovieCategory.now_playing, count, page);
            NowPlaying.results = NowPlaying.results.OrderByDescending(x => x.release_date).ToArray();

            var data = new VM_LandingPage()
            {
                CustomCollections = await _context
                                           .Collection
                                           .Include(c => c.MovieCollection)
                                           .ThenInclude(m => m.Movie)
                                           .ToListAsync(),
                NowPlaying = NowPlaying,
                Popular = await _tmdbMovieService.MovieSearchAsync(MovieCategory.popular, count, page),
                TopRated = await _tmdbMovieService.MovieSearchAsync(MovieCategory.top_rated, count, page),
                Upcomming = Upcomming,
                Horror = await _tmdbMovieService.MovieSearchByGenre("27,53", count),
                TvPopular = await _tmdbMovieService.TVSearchAsync(TVCategory.popular, count, page),
                NetflixOriginals = await _tmdbMovieService.TvDiscoverAsync("&with_networks=213", 1, count),
                NetflixGems = await _tmdbMovieService.TvDiscoverAsync("&sort_by=vote_average.desc&timezone=America%2FNew_York&vote_average.gte=7&vote_count.gte=5&with_networks=213&include_null_first_air_dates=false&with_watch_monetization_types=flatrate&with_status=0&with_type=0", 1, 8)

            };
            return View(data);
        }

        public IActionResult About()
        {
            return View();
        }

        public async Task<IActionResult> Search(string query, int page)
        {
            if (page == 0)
                page = 1;

            QueryAll queryResult = await _tmdbMovieService.QueryAll(query, page);
            queryResult = _dataMappingService.MapQueryAllDetails(queryResult);
            ViewData["query"] = query;
            ViewData["page"] = page;
            return View(queryResult);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/About.cshtml
<section class="relative text-center bg-blog pt-4">
    <div class="container pt-5">
        <div class="jumbotron text-center">
            <h1>
                <small>hello</small><span class='font-weight-bold'>I coded this</span>
            </h1>
        </div>
    </div>
</section>

<section class="bg-light section-xl">
    <ol class="breadcrumb text-center">
        <li>
            <a asp-action="Index"
               asp-controller="Home">Home</a>
        </li>
        <li class="active">About</li>
    </ol>
</section>
<section class="section section-inset-1">
    <div class="container">
        <h2 class="text-center">Nice to meet you</h2>
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8 col-lg-offset-2">
                <div class="thumbnail">
                    <img class="rounded-circle profilepic" src="~/images/profilePicMike.jpg" alt="">
                    <div class="caption-mod-1">
                        <h4 class="text-center" >Mike Velasco</h4><h6 class="text-center text-gray">Aspiring .Net Developer</h6>
                        <p class="text-md-left">
                            Thanks for checking out my demo project!
                            It is in early state of the app and 
                            I plan to implement some cool features in the future.
                            This is an application that uses Tmdb's Api to 
                            fetch data and present it to the user, Bootstrap and 
                            custom css is used in the front end and .Net 5 , 
                            EF Core with postgress at the backend
                        </p>
                        <p class="text-md-left">I made this app as part of CoderFoundry's Self Paced coding bootcamp, I hope that you enjoyed clicking through things and searching for your favorite Movie, TV shows and actors. I definately learned alot in building this app specificaly in the .Net web tech stack</p> 
                        <p> You can check out my full portfolio site at <a href="https://codingme.dev/">https://codingme.dev/ </a>  to see my other projects.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Home/Search.cshtml
@using ReelJunkies.Models.TmDb
@using ReelJunkies.Enums
@model QueryAll



<section class="relative text-center bg-blog pt-4">
    <div class="container pt-md-5">
        <div class="jumbotron text-center">
            <h1>
                <small>Here’s what we found on</small>
                <span class='font-weight-bold'>@ViewData["query"]</span>
            </h1>
        </div>
    </div>
</section>

<section class="bg-light section-xl">
    <ol class="breadcrumb text-center">
        <li>
            <a asp-controller="home"
               asp-action="index">Home</a>
        </li>
        <li class="active">Search Results</li>
    </ol>
</section>
<section class="section section-xxl bg-default">
    <div class="container">
        <h2>Search Results</h2>
        <div class="row justify-content-center">
            <div class="col-12">
                <!-- RD Search-->
                <form class="rd-form rd-search rd-form-inline"
                      asp-action="Search"
                      method="get">
                    <div class="form-wrap">
                        <label class="form-label"
                               for="rd-search-form-input">
                            Search
                        </label>
                        <input class="form-input"
                               id="rd-search-form-input"
                               type="text"
                               name="query"
                               value="@ViewData["Query"]"
                               autocomplete="off">
                    </div>
                    <div class="form-wrap form-button">
                        <button class="btn btn-success btn-sm btn-min-width-xs"
                                type="submit">
                            Search
                        </button>
                    </div>
                </form>
                <div class="rd-search-results"></div>
                <ul>
                    @foreach (var result in Model.results)
                    {
                        <li>
                            @if (result.media_type == MediaType.person.ToString())
                            {
                                <a class="row mb-4 justify-content-center"
                           asp-action="Details"
                           asp-route-id="@result.id"
                           asp-controller="Actors">
                                    <img class="col-sm-4 col-md-3 col-lg-2"
                                 src="@result.profile_path" />
                                    <div class="col-8">
                                        <h6 class="text-capitalize">
                                            @result.media_type
                                        </h6>
                                        <h5>@result.name</h5>
                                    </div>
                                </a>
                            }
                            else
                            {

                                <a class="row mb-4 justify-content-center"
                           asp-action="Details"
                           asp-route-id="@result.id"
                           asp-controller="Movies">
                                    <img class="col-sm-4 col-md-3 col-lg-2 "
                                 src="@result.poster_path" />
                                    <div class="col-8">
                                        <h6 class="text-capitalize">@result.media_type</h6>
                                        <h5>@result.title</h5>
                                        <div class="text-gray">@result.release_date</div>
                                        <div class="clamp">@result.overview</div>
                                    </div>
                                </a>
                            }
                        </li>
                    }
                </ul>


                <p>
                </p>
                @if (@Model.total_pages > 1)
                {
                   
                    <ul class="pagination pagination-center mt-5">
                        @if (@Model.page == 1)
                        {
                        <li class="disabled text-center"><span class="page-item"></span></li>
                        }
                        else
                        { 
                        <li class="page-item text-center">
                            <a asp-route-page="@(Model.page-1)"
                                   asp-action="search"
                                   asp-route-query="@ViewData["query"]"
                            class="page-item text-center"></a>
                            </li>
                        }
                        <li class="disabled text-center"><span class="page-item">@Model.page</span></li>
                        @for (var i = @Model.page +1; i <= @Model.total_pages && i <= @Model.page + 5; i++)
                        {
                            <li><a asp-route-page="@i"
                                   asp-action="search"
                                   asp-route-query="@ViewData["query"]"
                                class="page-item text-center">@i
                                </a>
                                </li>
                        }
                        @if (@Model.page == @Model.total_pages)
                       {
                        <li><a class="page-item text-center disabled" ></a></li>
                       }
                        else
                        {
                        <li>
                            <a asp-route-page="@(Model.page+1)"
                                   asp-action="search"
                                   asp-route-query="@ViewData["query"]"
                            class="page-item text-center">
                        </a>
                        </li>
                        }
                    </ul>
                   
                }
            </div>
        </div>
    </div>
</section>

@section Scripts{

<script src="/js/pagination.js"></script>
}